### PR TITLE
Grammar

### PR DESCRIPTION
**Pull request by Jonta**
Period after exclamation mark removed

### CODE REVIEW

**Comment by Jonta** [comment]
Hm. Why wasn't this merged?

**Comment by Dubwise56** [comment]
its just a full stop, not really needed

**Comment by Jonta** [comment]
Pipeline's not as simple as clickin' a button?

**Comment by Dubwise56** [comment]
dont see a change for a pipeline

**Comment by Dubwise56** [comment]
oh also full stops after an exclamation mark is wrong, thought it was but i googled just to make sure

**Comment by Dubwise56** [comment]
thats weird i don't know how a full stop got in there, i didn't even see it, some other dude must have added it with a push sometime, which is why i dont usually accept them and ignore them

**Comment by Dubwise56** [comment]
oh and yeah i would have to marge to this marge to my source marge back again and its easier to just remove it in my source

**Comment by Jonta** [comment]
Looks like an automatic thing that doesn't understand exclamation marks then, seeing as there's one in https://github.com/Dubwise56/Dubs-Bad-Hygiene/blob/master/README.md as well

**Pull request closed without merging**
